#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2

# If the control reaches this step, the service can be enabled and started
systemctl --user enable --now webtop.service

if [ -f "phonebook.env" ]; then
    systemctl --user enable --now phonebook.timer
    if systemctl --user is-active --quiet phonebook.timer; then
        systemctl --user restart phonebook.timer
    fi
else
    if systemctl --user is-active --quiet phonebook.timer; then
        systemctl --user disable --now phonebook.timer
    fi
fi
