#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os
import string
import secrets

try:
    secrets_env = agent.read_envfile("secrets.env")
except FileNotFoundError:
    # Generate a new API token
    postgres_password = secrets.token_urlsafe(32)
    secrets_env = {
        "POSTGRES_PASSWORD": postgres_password,
    }
    agent.write_envfile("secrets.env", secrets_env)
